---
- hosts: all
  become: yes
  vars_files:
  - vars.yml

  tasks:
  - name: Print variables from vars_files
    ansible.builtin.debug:
      msg: "load: {{ load }}, Database: {{ database_name }}"
  
  - name: Ensure chrony (for time synchronization) is installed.
    ansible.builtin.apt:
      name: chrony
      state: present

  - name: Ensure chrony is running.
    service:
      name: chronyd
      state: started
      enabled: yes
  